import type { Metadata } from "next";
import Link from "next/link";
import { LegalPage, LegalH2 } from "@/components/LegalPage";

export const metadata: Metadata = {
  title: "Giveaway Official Rules",
  description: "Official rules for Binder Sync giveaways and promotions.",
};

export default function GiveawayRulesPage() {
  return (
    <LegalPage title="Giveaway Official Rules" updated="July 16, 2026">
      <p>
        <strong>NO PURCHASE NECESSARY TO ENTER OR WIN. A PURCHASE DOES NOT INCREASE YOUR CHANCES
        OF WINNING.</strong>
      </p>
      <p>
        These rules apply to promotional giveaways run by Binder Sync (&ldquo;Sponsor&rdquo;) at
        bindersync.com. Each giveaway&rsquo;s announcement states its specific entry period,
        prizes, and number of winners; together with these rules, that announcement forms the
        official rules for that giveaway.
      </p>

      <LegalH2>Eligibility</LegalH2>
      <p>
        Open to legal residents of the United States who are 18 years or older at the time of
        entry. Void where prohibited by law. Employees of the Sponsor and their immediate family
        members are not eligible.
      </p>

      <LegalH2>How to enter</LegalH2>
      <p>
        Unless the giveaway announcement says otherwise, enter by submitting your email address
        on the <Link href="/giveaway">giveaway page</Link> during the entry period stated in the
        announcement, or by creating a free Binder Sync account during that period — either
        counts, and no payment of any kind is required. One entry per person regardless of
        method; entries generated by scripts, bots, or multiple addresses/accounts will be
        disqualified. Email addresses submitted for entry are used only to administer the
        giveaway (winner notification) and are not added to marketing lists without separate
        consent.
      </p>

      <LegalH2>Prizes</LegalH2>
      <p>
        Prizes are subscription benefits for the Binder Sync service, delivered as promotion
        codes or account credits — for example: 50% off one month of Pro or Master (approximate
        retail value $1.50–$3.00), one free month of Pro or Master (ARV $3.00–$6.00), or one free
        year of Master (ARV $72.00). The exact prizes and number of winners are stated in each
        giveaway&rsquo;s announcement. Prizes are non-transferable, have no cash value, and cannot
        be exchanged for cash or other goods. Sponsor may substitute a prize of equal or greater
        value if a stated prize becomes unavailable.
      </p>

      <LegalH2>Winner selection &amp; notification</LegalH2>
      <p>
        Winners are selected at random from eligible entries within 7 days after the entry period
        ends and are notified at their account email address. If a winner does not respond within
        7 days of notification, or is ineligible, an alternate winner may be selected. Odds of
        winning depend on the number of eligible entries received.
      </p>

      <LegalH2>General conditions</LegalH2>
      <p>
        By entering, you agree to these rules and to the Sponsor&rsquo;s{" "}
        <Link href="/terms">Terms of Service</Link> and{" "}
        <Link href="/privacy">Privacy Policy</Link>. Sponsor may cancel, suspend, or modify a
        giveaway if fraud or technical failure compromises its integrity. Winners are responsible
        for any taxes on prizes. This promotion is in no way sponsored, endorsed, administered
        by, or associated with Nintendo, Creatures, GAME FREAK, The Pokémon Company, Stripe, or
        any social-media platform on which it may be announced.
      </p>

      <LegalH2>Sponsor &amp; contact</LegalH2>
      <p>
        Binder Sync, bindersync.com. Questions about a giveaway? See the{" "}
        <Link href="/contact">contact page</Link>.
      </p>
    </LegalPage>
  );
}
